### HOW TO BEGIN

You can run globalmon using the provisioning command:
```bash
cloudmon --config etc/sample_config.yaml --inventory etc/inventory_quickstart/ --insecure globalmon provision
```

Here `sample_config` is the cloudmon config. Make sure the path for globalmon config is proper and complete. 

### CONTAINER CRASHES

Most likely it is a globalmon configuration issue. 

Here are some of the factors causing the issue:
1. Globalmon configuration is not loaded. Check if the file is at the volume which is mapped to the config location in the command.
2. The URLs are not properly written. Check if the URLs are complete beginning with http or https.
3. Statsd initialization fails. Check if statsd is reachable at the host mentioned in the config file.

Finally, try to run the docker command manually instead of the service. 
To do this, let's first copy the globalmon-config that was generated by cloudmon and paste it at a convinient location, say, `/home/ubuntu/config.yaml`. Now, we do not need to add the custom option `--config` with the docker command and can change the entry command to `/bin/bash` so that the container output can be checked using the following command.

```bash
docker run --name "cloudmon_globalmon" -v /home/ubuntu/config.yaml:/usr/app/globalmon/config.yaml -v /var/log/globalmon:/var/log/globalmon -it quay.io/stackmon/globalmon:change_12_latest /bin/bash
```

Check that the printed config matches the config file.

Finally, go through the errors.

### EXAMPLE

An error example could be:
```
Traceback (most recent call last):
  File "/usr/local/bin/globalmon", line 33, in <module>
    sys.exit(load_entry_point('globalmon==0.1.0', 'console_scripts', 'globalmon')())
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/globalmon-0.1.0-py3.13.egg/globalmon/server.py", line 99, in main
    globalmonWorker = GlobalmonWorker(config)
  File "/usr/local/lib/python3.13/site-packages/globalmon-0.1.0-py3.13.egg/globalmon/globalmon_worker.py", line 30, in __init__
    self.statsd_client = initialize_statsd_client(
                         ~~~~~~~~~~~~~~~~~~~~~~~~^
        config["statsd"]["host"], config["statsd"]["port"])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/globalmon-0.1.0-py3.13.egg/globalmon/utils.py", line 94, in initialize_statsd_client
    return statsd.StatsClient(host, port)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/statsd/client/udp.py", line 32, in __init__
    family, _, _, _, addr = socket.getaddrinfo(
                            ~~~~~~~~~~~~~~~~~~^
        host, port, fam, socket.SOCK_DGRAM)[0]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socket.py", line 975, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
```

This is statsd config error. Here, the statsd host is unreachable. In production, use the statsd IP or URL.
In case of development where statsd may be running on the same machine in a container called `graphite` (say), the hostname can then be just `graphite` PROVIDED the globalmon container is run in the same network. Add the `graphite` container to a network, for eg., `my_custom_network`, and then add the network to globalmon container at run time.

```bash
docker network create my_custom_network
docker network connect my_custom_network graphite
docker run --name "cloudmon_globalmon" --network my_custom_network -v /home/ubuntu/config.yaml:/usr/app/globalmon/config.yaml -v /var/log/globalmon:/var/log/globalmon -it quay.io/stackmon/globalmon:change_12_latest /bin/bash
```
